/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scraper;

import java.io.IOException;

public class App {
  public static void main(String[] args) throws IOException {
    final FFWInfo ffwInfo = new FFWInfo();
    System.out.println(ffwInfo.getPlantOfTheMonth());
    System.out.println(ffwInfo.getAnimalOfTheMonth());
    ffwInfo.getDidYouKnowFacts().forEach(System.out::println);

    final EventInfo eventInfo = new EventInfo();
    eventInfo.getEvents().forEach(System.out::println);
  }
}
